version: "3.9"

services:
    api:
        container_name: cod-users-api
        build: .
        volumes:
            - .:/go/src
        environment:
            - APPLICATION_ENV=development
        ports:
            - "8080:8080"
        networks:
            - cod-users-api-net

    mysql:
        container_name: cod-users-mysql
        build: .docker/mysql
        command: --innodb-use-native-aio=0
        restart: always
        tty: true
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        ports:
            - "33060:3306"
        environment:
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - cod-users-api-net

networks:
    cod-users-api-net:
        driver: bridge
